### ISSUE TITLE
remove underbar from slack message

### ISSUE THREAD

**Issue by kykim79** [kykim79/BitcoinTracker#13]
안드로이드에서는 slack message에 underbar를 사용하면 이탤릭으로 표시되지만 그외의 기기(pc, mac, ios)에서는  변환되지 않고 그대로 표시됨. 안드로이드버전
 slack의 버그로 보이므로 underbar 제거가 필요.

**Comment by riopapa** [comment]
markdown 뿐아니라 leading blank 같은 경우도 안드로이드에선 제대로 표시됨.
document에서도 markdown을 지원하는 것으로 되어 있으나, 다른 기기에서 제대로 표시되고 있지 않는 것일 뿐임.
그러나, 이러한 문제를 당분간 해결하지 않겠다고 하였으므로, 일단 markdown 부분은 제거하기로 함
