### ISSUE TITLE
cannot use currency folder as logger path

### ISSUE THREAD

**Issue by riopapa** [kykim79/BitcoinTracker#16]
logger path에 dynamic하게 currency 를 적용할 수 없어서 log4js.configure에 기능 추가하려 함

**Comment by riopapa** [comment]
현재는 configure에 파일을 assign하고 있는데, 다음 과 같이 바꾸려 함

1. loggerConfig.json을 읽어 들인 후
2. filename을 js 자체에서 지정
3. log4js.configure에 적용

(CONFIG, LOGGER_CONFIGFILE, LOGGER_OUTFILE 환경변수 이용)

**Comment by kykim79** [comment]
변경 전/후 내용을 좀 더 잘 파악할 수 있게 수정했습니다.
